Marking AutoClient assembly as experimental and adding README to the package
dotnet/extensions pull request #4512
Opened 2023-10-04 21:26 UTC by joperezr

Marking AutoClient as experimental for November, and adding README.md file so that it contains basic documentation for consumption.

2023-10-04 23:31 UTC, joperezr commented
@sebastienros we may want to add to the readme somewhere that we are now also escaping special characters on parameters in some cases. We probably want to wait for your PR to go in first, and then I can update the README as a follow up PR

2023-10-05 02:31 UTC, geeknoid commented
This is against the agreement we reached with Steve and David, we should not be marking anything in dotnet/extensions experimental at this point.

2023-10-05 04:10 UTC, joperezr commented
I think there is a misunderstanding here. During last week's tactical sync we agreed that AutoClient was the only assembly which was "okay" to make experimental given the fact that it is in its own assembly and nothing depends on it, and we also chatted with @davidfowl and said we would mark this as stable sometime next year, and you said that would be okay. Am I missing something here?

2023-10-05 04:22 UTC, davidfowl commented
I think we said we would leave it as non-experimental and do our best to find any API gaps in the short term, potentially making breaking changes if we need to (which we hopefully don't).

2023-10-05 04:25 UTC, joperezr commented
I just checked the recording and we did say we would mark it as experimental but that's okay, maybe you guys had a follow up chat where the decision was reversed 😝. I'll make the required changes here then.

2023-10-05 17:39 UTC, joperezr commented
API is no longer experimental. @geeknoid and @dbarbosapn I'd appreciate if we can validate that we are okay with the contents of the README file 😃

2023-10-06 01:27 UTC, geeknoid commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/Microsoft.Extensions.Http.AutoClient.csproj
> +    <InjectSharedDiagnosticIds>true</InjectSharedDiagnosticIds>
No longer needed.

2023-10-06 01:29 UTC, geeknoid commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +This package allows creating efficient HTTP auto clients with minimal code. The client code is generated at compile time, or while editing if analyzers are enabled.
```suggestion
This package allows creating efficient HTTP clients for existing REST APIs with minimal code. The client code is generated at compile time, is highly efficient, and integrates with modern telemetry patterns.
```

2023-10-06 01:30 UTC, geeknoid commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +By default, the generated client would be of type `MyDependencyClient` (Interface name without the `I`). If you need to use a different name for the dependency name, then you can use the different Au
```suggestion
By default, the generated client would be of type `MyDependencyClient` (Interface name without the `I`). If you need to use a different name for the dependency name, then you can use the different AutoClient constructors:
```

2023-10-06 17:58 UTC, joperezr commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/Microsoft.Extensions.Http.AutoClient.csproj
> +    <InjectSharedDiagnosticIds>true</InjectSharedDiagnosticIds>
```suggestion
```

2023-10-06 23:44 UTC, Tratcher commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +### Install the package
Seems redundant?
```suggestion
## Install the package
```

2023-10-06 23:44 UTC, Tratcher commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +### Defining a client
Same here:
```suggestion
## Defining a client
```

2023-10-06 23:45 UTC, Tratcher commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/Microsoft.Extensions.Http.AutoClient.csproj
> +    <PackageReadmeFile>README.md</PackageReadmeFile>
No longer needed
```suggestion
```

2023-10-06 23:45 UTC, Tratcher commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/Microsoft.Extensions.Http.AutoClient.csproj
> +    <None Include="README.md" Pack="true" PackagePath="\" />
```suggestion
```

2023-10-17 19:35 UTC, danmoseley commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +The first step for generating an auto client, is to define an interface[^1] that describes the client. The interface must be marked with the `[AutoClient]` attribute.
```suggestion
The first step to generate a client is to define an interface[^1] that describes the client. The interface must be marked with the `[AutoClient]` attribute.
```

2023-10-17 19:36 UTC, danmoseley commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +[^1]: The attribute must be used in interfaces, not classes.
```suggestion
[^1]: The attribute is only supported on interfaces.
```

2023-10-18 06:47 UTC, dbarbosapn requested changes
Just couple comments 👍  Thanks a lot for this contribution 🙇

2023-10-18 06:47 UTC, dbarbosapn commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +The first step to generate a client is to define an interface that describes the client. The interface must be marked with the `[AutoClient]` attribute[^1].
I'm wondering if the brackets should be removed or add ("MyHttpClient") here as well. I know there's an example below but quick readers might just see "[AutoClient]" and go with that. No strong opinion though :)

2023-10-18 06:47 UTC, dbarbosapn commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +To send a payload with your request, you mus tuse the `BodyAttribute` on a method parameter. If you don't pass any parameter to it, it will consider the content type is JSON, serializing your paramet
typo here, "mus**t** use"

2023-10-18 06:47 UTC, dbarbosapn commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +With the `HeaderAttribute`, you can receive the value for a header from the attributes of your Auto Client method. You must pass the header name to its constructor.
I think it's worth mentioning that the value is not serialized! Any complex structures passed as an header value will just have its "ToString()" method called.

2023-10-18 06:47 UTC, dbarbosapn commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +Query parameters must be defined using the `QueryAttribute`. If not specified in the attribute's constructor, the parameter name will be used as the query key.
Same as for the header values.

2023-10-18 06:49 UTC, davidfowl commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +builder.Services.AddMyDependencyClient();               // <-- Registers the Auto Client in the DI container.
?
```suggestion
builder.Services.AddMyHttpClient();               // <-- Registers the Auto Client in the DI container.
```

2023-10-18 06:50 UTC, davidfowl commented on src/Libraries/Microsoft.Extensions.Http.AutoClient/README.md
> +app.MapGet("/ProcessUsers", async ([FromServices] IMyDependencyClient client) =>
```suggestion
app.MapGet("/ProcessUsers", async (IMyDependencyClient client) =>
```

2023-10-22 00:00 UTC, geeknoid commented
AutoClient is being removed.

2023-10-22 00:00 UTC, closed without merging