Expose HTTP resilience handler (#4759)
dotnet/extensions pull request #4763
Opened 2023-11-28 15:24 UTC by kmcclellan

2023-11-28 15:48 UTC, kmcclellan commented
> Newly added symbol 'Microsoft.Extensions.Http.Resilience.ResilienceHttpMessageHandler' must be marked as experimental

Should that apply for types that have had access modifier changes?

2023-11-28 18:35 UTC, joperezr commented
@kmcclellan thanks so much for your proposal and for the contribution. I realize that we don't have this covered in our docs on this repo yet (I'll fix that), but in dotnet/extensions we follow the same API review process than the[ one used in aspnetcore repository](https://github.com/dotnet/aspnetcore/blob/main/docs/APIReviewProcess.md). This essentially means that when we want to add a new API, we should just make sure that it is approved by the API Review board before we can take a change that adds it.

It's still great that you already went and created the PR as that can be used during the review process in case there are any implementation questions. @martintmk will work on getting this API proposal reviewed and approved, so that we can take this change. I will mark this PR as No Merge for now while the API process unfolds.

2023-11-29 07:05 UTC, martintmk requested changes

2023-11-29 07:05 UTC, martintmk commented on src/Libraries/Microsoft.Extensions.Http.Resilience/Resilience/ResilienceHttpMessageHandler.cs
>          _pipelineProvider = pipelineProvider;
Since this is now internal, please validate the arguments.

2023-11-29 07:05 UTC, martintmk commented on src/Libraries/Microsoft.Extensions.Http.Resilience/Resilience/ResilienceHttpMessageHandler.cs
> +    public ResilienceHttpMessageHandler(ResiliencePipeline<HttpResponseMessage> pipeline)
Also validate that pipeline is not null.

2023-11-29 07:09 UTC, martintmk commented
@joperezr , @kmcclellan 

The exposed API is pretty well aligned with [`PolicyHttpMessageHandler`](https://github.com/dotnet/aspnetcore/blob/5b1ad1ee4934be7d587e50670524876763cd45eb/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L74) that uses Polly v7. This just adds even smaller subset of APIs for Polly v8 scenarios.

I believe this handler can be used for valid scenarios and bridges some feature gaps compared to the older library.

2024-01-09 19:21 UTC, closed without merging