Rename metrics for Resource Monitoring
dotnet/extensions pull request #5309
Opened 2024-07-25 15:39 UTC by evgenyfedorov2

Fixes #5113 

1. Renamed metrics
2. Introduced more specific metrics for container related measurements to distinguish process vs. container (cgroup).

2024-07-26 05:20 UTC, RussKie requested changes
This change looks like it potentially may be a breaking change. Metrics are kind part of the public surface - i.e., documentations, dashboards and other monitoring systems depend on existing/published metrics.

Unfortunately the original issue doesn't provide great level of detailed information on the underlying issue(s), scenarios where and how it manifests, how it affects customers, etc.

Could you please provide more information and assessment of the change in the following form:
- Customer Imparct - how would this change affect existing customers?
- Is this a regression? If yes, when was it introduced?
- How risky is this change?

Thank you.

I'm blocking the merge to understand the risks and impacts and stop an accidental merge.

2024-07-26 09:21 UTC, evgenyfedorov2 commented
@RussKie, here you are:
- Customer Impact - Monitoring dashboards will break, it requires customers to fix the dashboards.
- Is this a regression? - No
- How risky is this change? - Not sure how many customers we have for those two `ObservableGauge`metrics (I understand those are pretty new and not widely adopted), but I suggest making the change ASAP to avoid onboarding even more customers to incorrect metric names.

2024-07-26 09:26 UTC, evgenyfedorov2 commented
> Unfortunately the original issue doesn't provide great level of detailed information on the underlying issue(s), scenarios where and how it manifests, how it affects customers, etc.

It does not affect customers as such, they can live with it forever and be happy :) However, it is just semantically incorrect to have `process.*` names for metrics measuring CPU/Memory utilization of the whole container or control group.

2024-07-29 01:28 UTC, RussKie commented
@JamesNK @joperezr any thoughts on this?

2024-07-29 12:51 UTC, JamesNK commented
It's definitely a breaking change. It needs to be documented as a breaking change and the mitigations required to work around it be in release notes.

You could require people to update whatever consumes the metrics to make a fix. If there are people who can't do that then you could add an app context switch that someone can set in their app to keep old behavior.

2024-07-29 22:58 UTC, joperezr commented
@evgenyfedorov2 can you please go into a bit more detail as to what is the motivation behind this change? Is it mostly just that the naming is inaccurate so we want to fix it? We should get the full motivation so we can evaluate if this is worth the breaking change.

2024-08-06 04:55 UTC, RussKie commented on src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceUtilizationInstruments.cs
> +    public const string ProcessMemoryUtilization = "dotnet.process.memory.virtual.utilization";
Should we decorate these as `[Obsolete]` to indicate they shouldn't be used?
![image](https://github.com/user-attachments/assets/2fae4224-45f6-474f-a20e-db9a6cd3dabc)

2024-08-06 14:28 UTC, closed without merging