Resource Monitoring metrics on Window - remove multiplication by 100
dotnet/extensions pull request #5473
Opened 2024-10-06 19:38 UTC by evgenyfedorov2

Fixes #5472

2024-10-07 23:00 UTC, RussKie commented
What's the plan to notify the existing consumers? I imagine dashboards will be affected...

2024-10-08 09:08 UTC, evgenyfedorov2 commented
> What's the plan to notify the existing consumers? I imagine dashboards will be affected...

Yes, they will. The only notification mechanism I see is Release Notes.

2024-10-08 11:55 UTC, talinas commented on src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsContainerSnapshotProvider.cs
> +                _memoryPercentage = Math.Min(Hundred, memoryUsage / _memoryLimit);
Considering that the first parameter `Hundred` (defined above as `double 100.0d`), was used to 'cap' utilization at 100.0 in the previous version, wouldn't it make sense to 'cap' it at 1.0 going forward?

2024-10-10 22:18 UTC, RussKie requested changes
I'm blocking this until this is discussed at the Tactical Sync.

2024-10-11 18:34 UTC, joperezr commented
> > What's the plan to notify the existing consumers? I imagine dashboards will be affected...
> 
> Yes, they will. The only notification mechanism I see is Release Notes.

Yeah so I don't feel comfortable doing this, particularly as we know it is a package that is used internally and we only support the latest version, so we can't make these type of breaking changes (or at least can't take it lightly). Is there a way to do this in a non-breaking way? For instance, we could use quirks where the behavior is preserved, and people that want the new behavior can set an appconfig switch to choose the other behavior. Then we can decide when to switch the defaults.

2024-10-28 00:13 UTC, RussKie commented
@evgenyfedorov2 @joperezr what was the decision on this change?

2024-10-28 18:18 UTC, joperezr commented
We talked about it in the last tactical sync and agreed we couldn't take the change as-is. We suggesting to potentially quirk this and then next major we could switch from opt-in to opt-out. I believe @evgenyfedorov2 was going to work on that.

2024-10-29 09:11 UTC, evgenyfedorov2 commented
> We talked about it in the last tactical sync and agreed we couldn't take the change as-is. We suggesting to potentially quirk this and then next major we could switch from opt-in to opt-out. I believe @evgenyfedorov2 was going to work on that.

I was not able to join the meeting, just watched the recording, but I did not hear my argument being addressed. The argument is this:
With the quirk, we will eventually make the breaking change some time later when we perhaps have much larger user base. E.g.:
- if we make this change today, ~0 external customers will be affected (because the Windows metrics part is a brand new feature, only about 2-3 months old) and up to 100 internal ones.
- if we do this change later in 1-2 years (whenever the next major release is), 100-1000s external and 100+ internal customers will be affected. I don't believe many will opt-in to the right behavior, everyone will just use the default and incorrect behavior.

If you still prefer to support the incorrect behavior, one alternative is to introduce the quirk as proposed, but make the right (new) behavior default, so new customers would onboard to the right behavior by default, while the old customers will get a chance to opt-in to the incorrect behavior if they really want to. What do you think?

2024-10-29 18:05 UTC, joperezr commented
There are two things to consider here:

- Whether or not the new behavior is the correct one that our customers will prefer, as opposed to the previous one. If we aren't sure yet, then having the new behavior be opt-in helps since it doesn't break existing customers, and it allows you to have a controlled amount of customers explicitly try out the new behavior and listen to feedback.
- Whether or not we can give existing customers the heads up of the change. If we decide this to be opt-out, we should be sure to communicate to all existing customers about the change, as this would break all existing dashboards. If we don't think we can confidently raise awareness of this, I'd prefer this not to be an opt-out behavior.

Ultimately, there is no good answer here that allows you to change behavior, and at the same time provide great compat for existing customers via quirking. Another option that would allow you to do both of those things, would be to introduce net-new metrics, so customers dependent on existing metrics can continue to do so, and we can introduce new ones that provide the new values.

2024-10-30 07:10 UTC, evgenyfedorov2 commented
> * If we aren't sure yet

We are 100% sure, it is a bug. This is why this whole thing is confusing to me, generally, bugs are just fixed straight away, regardless whether customers relied on the buggy behavior or not.

2024-12-04 08:48 UTC, makazeu commented
Hi, any prorgess or update on this?

2024-12-04 09:17 UTC, evgenyfedorov2 commented
> Hi, any prorgess or update on this?

I have different priorities but will try to get back onto it in December/January

2025-01-02 14:21 UTC, evgenyfedorov2 commented on src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsContainerSnapshotProvider.cs
> +                _memoryPercentage = Math.Min(Hundred, memoryUsage / _memoryLimit);
Fixed

2025-01-02 14:22 UTC, evgenyfedorov2 commented
> I'm blocking this until this is discussed at the Tactical Sync.

As discussed, added a new property `UseZeroToOneRangeForMetrics`. The new (and correct) functionality is now opt-in

2025-01-13 11:09 UTC, talinas approved these changes

2025-01-14 08:03 UTC, haipz commented
> > I'm blocking this until this is discussed at the Tactical Sync.
> 
> As discussed, added a new property `UseZeroToOneRangeForMetrics`, so that the new (and correct) functionality is now opt-in

Should we set UseZeroToOneRangeForMetrics as a required option to ensure that people are notified of this breaking change?

2025-01-20 16:42 UTC, evgenyfedorov2 commented
> > > I'm blocking this until this is discussed at the Tactical Sync.
> > 
> > 
> > As discussed, added a new property `UseZeroToOneRangeForMetrics`, so that the new (and correct) functionality is now opt-in
> 
> Should we set UseZeroToOneRangeForMetrics as a required option to ensure that people are notified of this breaking change?

Eventually we will want to set `UseZeroToOneRangeForMetrics` = true by default, and later on remove that property completely. The `required` modifier might complicate things

2025-01-31 02:52 UTC, RussKie approved these changes

2025-01-31 02:52 UTC, merged

2025-02-02 23:22 UTC, RussKie commented
@evgenyfedorov2 please link here the PR updating the docs. Thank you.